name: mofsynth_adv_cli_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - tblite
  - tblite-python
  - pip
  - pip:
      - -e .
# - mofsynth_adv for pypi install